name: Java CI

on:
  workflow_dispatch:
  push:
  pull_request:
    branches: [ "master", "develop" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
          server-id: sonatype-nexus-staging # Value of the distributionManagement/repository/id field of the pom.xml
          server-username: CI_DEPLOY_USERNAME # env variable for username in deploy
          server-password: CI_DEPLOY_PASSWORD # env variable for token in deploy
          gpg-private-key: ${{ secrets.CI_GPG_PRIVATE_KEY }} # Value of the GPG private key to import
          gpg-passphrase: CI_GPG_PASSPHRASE # env variable for GPG private key passphrase

      - name: install, unit test, integration test
        run: mvn install -Dmaven.javadoc.skip=true -B -V

      - name: Release to maven central
        if: github.ref_name == 'master' && github.event_name != 'pull_request' && github.repository == 'swisspost/jsons2xsd-maven-plugin'
        run: |
          curl -s https://get.sdkman.io | bash
          source "$HOME/.sdkman/bin/sdkman-init.sh"
          sdk install groovy 3.0.8

          chmod +x ./maybe-release.sh
          ./maybe-release.sh
        env:
          CI_DEPLOY_USERNAME: ${{ secrets.CI_DEPLOY_USERNAME }}
          CI_DEPLOY_PASSWORD: ${{ secrets.CI_DEPLOY_PASSWORD }}
          CI_GPG_PASSPHRASE: ${{ secrets.CI_GPG_PASSPHRASE }}

      - name: After release
        run: bash <(curl -s https://codecov.io/bash)